name: Build and Publish
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:
          name: Build and push database
          command: |
            pwd
            cd mysql
            docker build -t anhhoang2910/dbmysql:latest .
            docker login -u ${username} -p ${password}
            docker push anhhoang2910/dbmysql:latest
workflows:
  build-and-publish:
    jobs:
      - build:
          filters:
            branches:
              only: main