name: Build and Publish
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker hub image
        run: |
          echo "The ${{ env.MYSQL_DATABASE }} event triggered this action."
          command: |
            pwd
            cd mysql
            docker build -t anhhoang2910/dbmysql:latest .
            docker login -u ${{env.USERNAME}} -p ${{env.PASSWORD}
            docker push anhhoang2910/dbmysql:latest